name: Notify Collaborators on Pull Request

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  notify-collaborators:
    runs-on: ubuntu-latest
    steps:
      - name: Notify collaborators via issue comment
        uses: actions/github-script@v7
        with:
          script: |
            // List of GitHub usernames to notify
            const collaborators = ['LETI-122607']; 

            if (collaborators.length > 0) {
              const mentionString = collaborators.map(u => `@${u}`).join(' ');
              const prNumber = context.payload.pull_request.number;
              const message = `Pull request #${prNumber} opened. Notifying: ${mentionString}`;

              // Leave a comment on the PR tagging collaborators
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: message
              });
            }
